# .travis.yml
language: node_js
node_js:
  - '6'
  - '8'
  - '9'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - openssl req -newkey rsa:2048 -nodes -keyout test.key -x509 -days 365 -out test.crt -subj /CN=localhost/C=fr/ST=rhone/L=lyon/O=atlantis-software/OU=synapps/emailAddress=test@localhost
script:
  - "npm run test-ci"
after_script: "npm install coveralls && cat ./test/coverage/lcov.info | coveralls"
