environment:
  matrix:
    - nodejs_version: "6.12"
    - nodejs_version: "7.10"
    - nodejs_version: "8.9"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set shrinkwrap false
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
version: "{build}"
