environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.8"
    - nodejs_version: "5.12"
    - nodejs_version: "6.12"
    - nodejs_version: "7.10"
    - nodejs_version: "8.9"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - openssl req -newkey rsa:2048 -nodes -keyout test.key -x509 -days 365 -out test.crt -subj /CN=localhost/C=fr/ST=rhone/L=lyon/O=atlantis-software/OU=synapps/emailAddress=test@localhost
  - npm config set shrinkwrap false
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
version: "{build}"
